### ISSUE TITLE
sense-sdk-android: App: Poor loading time

### ISSUE THREAD

**Issue by thkim-cochl** [cochlearai/sense-sdk-android#1]
SDK loading time is very slow than before.

**Comment by hyungui** [comment]
Yes, testing with Galaxy s7, it takes about 8-9 seconds after choosing event classes in the first page.

It looks like the app is stopped with some kind of error because there is no animation which indicates there is processing inside.

Temporary, including a progress bar or model loading page, should be helpful for the problem.

**Comment by thkim-cochl** [comment]
This is a model loading bottleneck.
https://github.com/cochlearai/sense-sdk-android/blob/v0.1/SampleApp/app/src/main/java/ai/cochlear/sdk/examples/sampleapp/EventActivity.java#L93-L94

I checked the model loading time cost with below's code:
```
        // Load the TensorFlow model.
        long startTime = SystemClock.uptimeMillis();
        model = cochl.getInstance().getModel("event");
        long endTime = SystemClock.uptimeMillis();
        Log.d(LOG_TAG, "Timecost to load model (ms): " + (endTime - startTime));
```

Result (6.4s)
```
2019-11-13 17:25:29.370 31569-31569/ai.cochlear.sdk.examples.sampleapp D/EventActivity: Timecost to load model (ms): 6428
```
